FROM alpine:3.9
RUN apk add --no-cache dumb-init rsync
RUN mkdir /data
RUN echo "uid = root" >>/etc/rsyncd.conf
RUN echo "fid = root" >>/etc/rsyncd.conf
RUN echo "[data]" >>/etc/rsyncd.conf
RUN echo "  path = /data" >>/etc/rsyncd.conf
RUN echo "  read only = false" >>/etc/rsyncd.conf
ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["/usr/bin/rsync", "--daemon", "--no-detach"]
