#!/bin/sh

set -e
mkdir -p /pipframer
touch /pipframer/.pipframer
rsync -z /pipframer/.pipframer rsync://root@localhost:873/data/pipframer/
rsync -rz rsync://root@localhost:873/data/pipframer /
command=$1
shift
pip ${command} --cache-dir /pipframer $*
rsync -rz /pipframer rsync://root@localhost:873/data/
