#!/bin/sh

set -e
if [ -z "$(docker ps -q -f name=nfcache)" ]; then
    docker run --rm -d --name nfcache -v nfcache:/data -p 873:873 nfcentral/nfcache:latest
fi
DOCKER_BUILDKIT=1 docker build --network host --target requirements -t {{name}}_requirements -f .nf/Dockerfile .
DOCKER_BUILDKIT=1 docker build --network host --target code -t {{name}}_code -f .nf/Dockerfile .
DOCKER_BUILDKIT=1 docker build --network host --target app_dev -t {{name}}_dev -f .nf/Dockerfile .
{{#features.jupyter}}
DOCKER_BUILDKIT=1 docker build --network host --target jupyter -t {{name}}_jupyter -f .nf/Dockerfile .
{{/features.jupyter}}
DOCKER_BUILDKIT=1 docker build --network host --target app -t {{name}} -f .nf/Dockerfile .
