#!/bin/sh

set -e

if [ "0" != "$#" ]; then
    docker run --rm -v "$(pwd)":/project ${NF_IMAGE}:${NF_VERSION} pipfreeze $*
    exit
fi

docker run --network host --rm {{name}}_requirements pip freeze >nf.pipfreeze
