#!/bin/sh

set -e

if [ "0" != "$#" ]; then
    docker run --rm -v "$(pwd)":/project nfcentral/nf:${NF_VERSION} pipfreeze $*
    exit
fi

docker run --network host --rm {{name}}_requirements cat /nf.pipfreeze >nf.pipfreeze
